'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34011
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace wsMWS_QA
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UsuarioMWS", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfMWService2"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UsuarioMWS
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BolAutenticadoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StrGUIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StrMensajeErrorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StrMotivoAccesoDenegadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StrPasswordField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StrUsuarioField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BolAutenticado() As Boolean
            Get
                Return Me.BolAutenticadoField
            End Get
            Set
                If (Me.BolAutenticadoField.Equals(value) <> true) Then
                    Me.BolAutenticadoField = value
                    Me.RaisePropertyChanged("BolAutenticado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StrGUID() As String
            Get
                Return Me.StrGUIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StrGUIDField, value) <> true) Then
                    Me.StrGUIDField = value
                    Me.RaisePropertyChanged("StrGUID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StrMensajeError() As String
            Get
                Return Me.StrMensajeErrorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StrMensajeErrorField, value) <> true) Then
                    Me.StrMensajeErrorField = value
                    Me.RaisePropertyChanged("StrMensajeError")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StrMotivoAccesoDenegado() As String
            Get
                Return Me.StrMotivoAccesoDenegadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StrMotivoAccesoDenegadoField, value) <> true) Then
                    Me.StrMotivoAccesoDenegadoField = value
                    Me.RaisePropertyChanged("StrMotivoAccesoDenegado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StrPassword() As String
            Get
                Return Me.StrPasswordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StrPasswordField, value) <> true) Then
                    Me.StrPasswordField = value
                    Me.RaisePropertyChanged("StrPassword")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StrUsuario() As String
            Get
                Return Me.StrUsuarioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StrUsuarioField, value) <> true) Then
                    Me.StrUsuarioField = value
                    Me.RaisePropertyChanged("StrUsuario")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="wsMWS_QA.iMWSecService")>  _
    Public Interface iMWSecService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/iMWSecService/GetTokenUsrPwd", ReplyAction:="http://tempuri.org/iMWSecService/GetTokenUsrPwdResponse")>  _
        Function GetTokenUsrPwd(ByVal Usuario As String, ByVal Password As String) As wsMWS_QA.UsuarioMWS
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/iMWSecService/GetUsrByToken", ReplyAction:="http://tempuri.org/iMWSecService/GetUsrByTokenResponse")>  _
        Function GetUsrByToken(ByVal strGUID As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/iMWSecService/ValidateUseApp", ReplyAction:="http://tempuri.org/iMWSecService/ValidateUseAppResponse")>  _
        Function ValidateUseApp(ByVal strGUID As String, ByVal strAppName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/iMWSecService/ValidateAction", ReplyAction:="http://tempuri.org/iMWSecService/ValidateActionResponse")>  _
        Function ValidateAction(ByVal strGUID As String, ByVal Action As String) As Boolean
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface iMWSecServiceChannel
        Inherits wsMWS_QA.iMWSecService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class iMWSecServiceClient
        Inherits System.ServiceModel.ClientBase(Of wsMWS_QA.iMWSecService)
        Implements wsMWS_QA.iMWSecService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetTokenUsrPwd(ByVal Usuario As String, ByVal Password As String) As wsMWS_QA.UsuarioMWS Implements wsMWS_QA.iMWSecService.GetTokenUsrPwd
            Return MyBase.Channel.GetTokenUsrPwd(Usuario, Password)
        End Function
        
        Public Function GetUsrByToken(ByVal strGUID As String) As String Implements wsMWS_QA.iMWSecService.GetUsrByToken
            Return MyBase.Channel.GetUsrByToken(strGUID)
        End Function
        
        Public Function ValidateUseApp(ByVal strGUID As String, ByVal strAppName As String) As Boolean Implements wsMWS_QA.iMWSecService.ValidateUseApp
            Return MyBase.Channel.ValidateUseApp(strGUID, strAppName)
        End Function
        
        Public Function ValidateAction(ByVal strGUID As String, ByVal Action As String) As Boolean Implements wsMWS_QA.iMWSecService.ValidateAction
            Return MyBase.Channel.ValidateAction(strGUID, Action)
        End Function
    End Class
End Namespace
