Imports Telerik.Web.UI
Imports System.Web.UI.DataVisualization.Charting
Imports System.Drawing
Imports System.Data.SqlClient



Partial Public Class ComparativaTemas
    Inherits System.Web.UI.Page
    Dim Param As Integer
    Dim Empresa As Integer
    Dim Sist As Integer

    Protected Overrides Sub InitializeCulture()
        If Not Session("Lenguaje") Is Nothing Then
            UICulture = Session("Lenguaje")
            Culture = Session("Lenguaje")
        End If
        MyBase.InitializeCulture()
    End Sub

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Try

            If Session("CON") = "OK" Then
                If Not Page.IsPostBack Then
                    Param = Request.Params("Tipo")
                    Empresa = Request.Params("Em")
                    Sist = Request.Params("Ses")
                    Session("CveSistema") = Sist

                    If Param = 99 Then
                        Dim Dt As New DataTable
                        Dt = CType(Session("DSBench"), DataTable)
                        'Dim Dt As New DataSet
                        'Dt = CType(Session("DSBench"), DataSet)

                        RadGrid1.DataSource = Dt
                        RadGrid1.DataBind()

                        For cont As Integer = 0 To RadGrid1.MasterTableView.AutoGeneratedColumns.Length - 1
                            Dim colDecimal As GridBoundColumn
                            colDecimal = RadGrid1.MasterTableView.AutoGeneratedColumns(cont)
                            colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Center
                            If cont = 0 Or cont = 1 Or cont = 2 Then
                                'Hacemos invisibles las claves
                                colDecimal.Visible = False
                            ElseIf cont = 3 Then 'Alineamos los temas
                                colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Left
                            ElseIf cont >= 4 Then
                                colDecimal.DataFormatString = "{0:N1}"
                            End If
                        Next
                        RadGrid1.Rebind()
                    ElseIf Param = 1 Then
                        Dim p(1) As SqlParameter
                        p(0) = New SqlParameter("@CveEmpresa", Empresa)
                        p(1) = New SqlParameter("@CVEPERFIL", Session("NUMPERFIL"))
                        Dim Ds As New DataSet
                        Ds = DatosBD.FuncionConPar("SP_BENCH_POR_TEMA", p, "")

                        RadGrid1.DataSource = Ds.Tables(0)
                        RadGrid1.DataBind()

                        For cont As Integer = 0 To RadGrid1.MasterTableView.AutoGeneratedColumns.Length - 1
                            Dim colDecimal As GridBoundColumn
                            colDecimal = RadGrid1.MasterTableView.AutoGeneratedColumns(cont)
                            colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Center
                            If cont = 0 Or cont = 2 Or cont = 4 Then 'Hacemos invisibles las claves
                                colDecimal.Visible = False
                            ElseIf cont = 5 Then 'Alineamos los temas
                                colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Left
                            End If
                            If cont >= 7 Then
                                If cont Mod 2 = 1 Then
                                    colDecimal.DataFormatString = "{0:N1}"
                                End If
                            End If
                        Next
                        RadGrid1.Rebind()
                    ElseIf Param = 2 Then
                        Dim ds As New DataSet
                        Dim PLoad(12) As SqlParameter
                        PLoad(0) = New SqlParameter("@TIPO", 0)
                        PLoad(1) = New SqlParameter("@CVEDIVISION", Session("CveUnidad"))
                        PLoad(2) = New SqlParameter("@CVEAGRUPADOPAIS", Session("CveAgrupado"))
                        PLoad(3) = New SqlParameter("@CVEPAIS", Session("CvePais"))
                        PLoad(4) = New SqlParameter("@CVEAREA", Session("CveTipo"))
                        PLoad(5) = New SqlParameter("@CVETERRITORIO", Session("CveTerritorio"))
                        PLoad(6) = New SqlParameter("@CVEREGION", Session("CveRegion"))
                        PLoad(7) = New SqlParameter("@CVESUBREGION", Session("CveSubRegion"))
                        PLoad(8) = New SqlParameter("@CVEEMPRESA", DBNull.Value)
                        'Se manda 3 directo para preguntamaster, en el SP viene definicion   4 abril 2018
                        PLoad(9) = New SqlParameter("@CVESISTEMA", Session("CveSistema"))


                        PLoad(10) = New SqlParameter("@CVEPERFIL", Session("NUMPERFIL"))
                        PLoad(11) = New SqlParameter("@USUARIO", Session("USUARIO"))
                        PLoad(12) = New SqlParameter("@IDIOMA", Session("Idioma"))


                        ds = DatosBD.FuncionConPar("SP_BUSQUEDA_PREGUNTAS", PLoad, "")

                        RadGrid1.DataSource = ds.Tables(0)
                        RadGrid1.DataBind()

                        For cont As Integer = 0 To RadGrid1.MasterTableView.AutoGeneratedColumns.Length - 1
                            Dim colDecimal As GridBoundColumn
                            colDecimal = RadGrid1.MasterTableView.AutoGeneratedColumns(cont)
                            colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Center
                            If cont = 0 Or cont = 2 Then 'Hacemos invisibles las claves
                                colDecimal.Visible = False
                            ElseIf cont = 1 Or cont = 3 Then 'Alineamos los temas
                                colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Left
                            End If
                            If cont >= 5 Then
                                If cont Mod 2 = 1 Then
                                    colDecimal.DataFormatString = "{0:N1}"
                                End If
                            End If
                        Next
                        RadGrid1.Rebind()
                    ElseIf Param = 3 Then
                        Dim ds As New DataSet
                        Dim PLoad(12) As SqlParameter
                        PLoad(0) = New SqlParameter("@TIPO", 1)
                        PLoad(1) = New SqlParameter("@CVEDIVISION", Session("CveUnidad"))
                        PLoad(2) = New SqlParameter("@CVEAGRUPADOPAIS", Session("CveAgrupado"))
                        PLoad(3) = New SqlParameter("@CVEPAIS", Session("CvePais"))
                        PLoad(4) = New SqlParameter("@CVEAREA", Session("CveTipo"))
                        PLoad(5) = New SqlParameter("@CVETERRITORIO", Session("CveTerritorio"))
                        PLoad(6) = New SqlParameter("@CVEREGION", Session("CveRegion"))
                        PLoad(7) = New SqlParameter("@CVESUBREGION", Session("CveSubRegion"))
                        PLoad(8) = New SqlParameter("@CVEEMPRESA", DBNull.Value)
                        PLoad(9) = New SqlParameter("@CVESISTEMA", Session("CveSistema"))
                        PLoad(10) = New SqlParameter("@CVEPERFIL", Session("NUMPERFIL"))
                        PLoad(11) = New SqlParameter("@USUARIO", Session("USUARIO"))
                        PLoad(12) = New SqlParameter("@IDIOMA", Session("Idioma"))

                        ds = DatosBD.FuncionConPar("SP_BUSQUEDA_PREGUNTAS", PLoad, "")

                        RadGrid1.DataSource = ds.Tables(0)
                        RadGrid1.DataBind()

                        For cont As Integer = 0 To RadGrid1.MasterTableView.AutoGeneratedColumns.Length - 1
                            Dim colDecimal As GridBoundColumn
                            colDecimal = RadGrid1.MasterTableView.AutoGeneratedColumns(cont)
                            colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Center
                            If cont = 0 Or cont = 2 Then 'Hacemos invisibles las claves
                                colDecimal.Visible = False
                            ElseIf cont = 1 Or cont = 3 Then 'Alineamos los temas
                                colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Left
                            End If
                            If cont >= 5 Then
                                If cont Mod 2 = 1 Then
                                    colDecimal.DataFormatString = "{0:N1}"
                                End If
                            End If
                        Next
                        RadGrid1.Rebind()
                    End If
                End If
            Else
                Session.Abandon()
                Response.Redirect("Acceso.aspx", True)
            End If
        Catch ex As Exception
            LError.Text = ex.Message
            LError.Visible = True
        End Try
    End Sub

    Private Sub RadGrid1_ItemDataBound(ByVal sender As Object, ByVal e As Telerik.Web.UI.GridItemEventArgs) Handles RadGrid1.ItemDataBound
        If e.Item.ItemType = GridItemType.Header Then
            For N As Integer = 6 To e.Item.Cells.Count - 1
                If e.Item.Cells(N).Text = "DIFERENCIA" Then
                    Session("SINCOLOR") = N
                End If
            Next

        ElseIf e.Item.ItemType = GridItemType.AlternatingItem OrElse e.Item.ItemType = GridItemType.Item Then
            If e.Item.Cells(6).Text = "99" Then ' SI ES GENERAL
                e.Item.Font.Bold = True
            End If

            For N As Integer = 6 To e.Item.Cells.Count - 1
                If IsNumeric(e.Item.Cells(N).Text) AndAlso e.Item.Cells(N).Text.Contains(".") AndAlso N <> Session("SINCOLOR") Then
                    e.Item.Cells(N).BackColor = GETCOLOR(e.Item.Cells(N).Text)
                    e.Item.Cells(N).ForeColor = GETCOLOR2(e.Item.Cells(N).Text)
                ElseIf Request.Params("Tipo") = 99 And Session("SINCOLOR") = N Then
                    e.Item.Cells(N).Font.Bold = True
                    If e.Item.Cells(N).Text > 0 Then
                        e.Item.Cells(N).ForeColor = Drawing.Color.Green
                    ElseIf e.Item.Cells(N).Text < 0 Then
                        e.Item.Cells(N).ForeColor = Drawing.Color.Red
                    End If
                End If
            Next
        End If
    End Sub

    Function GETCOLOR(ByVal Numero As Double) As System.Drawing.Color
        If Numero = 0 Then
            Return Drawing.Color.Gray
        ElseIf Numero > 0 And Numero <= 69.999999 Then
            Return Drawing.Color.Red
        ElseIf Numero >= 70.0 And Numero <= 79.999999 Then
            Return Drawing.Color.Yellow
        ElseIf Numero >= 80.0 And Numero <= 89.999999 Then
            Return Drawing.Color.Blue
        Else
            Return Drawing.Color.Green
        End If
    End Function

    Function GETCOLOR2(ByVal Numero As Double) As System.Drawing.Color
        If Numero = 0 Then
            Return Drawing.Color.White
        ElseIf Numero > 0 And Numero <= 69.999999 Then
            Return Drawing.Color.White
        ElseIf Numero >= 70.0 And Numero <= 79.999999 Then
            Return Drawing.Color.Black
        ElseIf Numero >= 80.0 And Numero <= 89.999999 Then
            Return Drawing.Color.White
        Else
            Return Drawing.Color.White
        End If
    End Function
End Class