Imports System.Web.UI.DataVisualization.Charting
Imports System.Drawing
Imports System.Data.SqlClient
Imports Telerik.Web.UI

Partial Public Class PAEvaluacion
    Inherits System.Web.UI.Page

    Dim AnioEstudio As Integer
    Dim CvePlan, CveObjetivo, CveIniciativa As String

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        If Not Page.IsPostBack Then
            CvePlan = Seguridad.Decriptar(CStr(Request.Params("P")), "DICOYES")
            CveObjetivo = Seguridad.Decriptar(CStr(Request.Params("O")), "DICOYES")
            CveIniciativa = Seguridad.Decriptar(CStr(Request.Params("I")), "DICOYES")
            LNumUsuario.Text = Seguridad.Decriptar(CStr(Request.Params("U")), "DICOYES")

            'Dim CONSULTA As String
            'CONSULTA = "SELECT CVEPLAN, PLANACCION FROM TblPA WHERE CVEPLAN=" & CvePlan
            'Cargar.ComboSentenciaTxt(RCBPlan, CONSULTA, "PLANACCION", "CVEPLAN", 2, False)


            Dim ds As New DataSet
            Dim P(1) As SqlParameter
            P(0) = New SqlParameter("@TIPO", 43)
            P(1) = New SqlParameter("@CVEPLAN", CvePlan)
            ds = DatosBD.FuncionConPar("SP_CONSULTAS_ENTREGAVIRTUAL", P, Lerror.Text)


            RCBPlan.DataSource = ds.Tables(0)
            RCBPlan.DataTextField = "PLANACCION"
            RCBPlan.DataValueField = "CVEPLAN"
            RCBPlan.DataBind()

            Dim ds2 As New DataSet
            Dim P2(1) As SqlParameter
            P2(0) = New SqlParameter("@TIPO", 44)
            P2(1) = New SqlParameter("@USUARIO", LNumUsuario.Text)
            ds2 = DatosBD.FuncionConPar("SP_CONSULTAS_ENTREGAVIRTUAL", P2, Lerror.Text)
            AnioEstudio = ds2.Tables(0).Rows(0).Item(0)


            LlenarObjetivos()
            LlenarIniciativas()
            LlenarGrid()
        End If
    End Sub

    Sub LlenarObjetivos()
        RCBObjetivo.Items.Clear()
        'Dim CONSULTA As String
        'CONSULTA = "SELECT CVEOBJETIVO, OBJETIVO FROM TblPAObjetivo WHERE CVEPLAN=" & RCBPlan.SelectedValue & " AND CVEOBJETIVO=" & CveObjetivo & " AND ANIOESTUDIO=" & AnioEstudio
        'Cargar.ComboSentenciaTxt(RCBObjetivo, CONSULTA, "OBJETIVO", "CVEOBJETIVO", 2, False)

        Dim ds As New DataSet
        Dim P(3) As SqlParameter
        P(0) = New SqlParameter("@TIPO", 45)
        P(1) = New SqlParameter("@CVEPLAN", RCBPlan.SelectedValue)
        P(2) = New SqlParameter("@CVEOBJETIVO", CveObjetivo)
        P(3) = New SqlParameter("@ANIOESTUDIO", AnioEstudio)
        ds = DatosBD.FuncionConPar("SP_CONSULTAS_ENTREGAVIRTUAL", P, Lerror.Text)


        RCBObjetivo.DataSource = ds.Tables(0)
        RCBObjetivo.DataTextField = "OBJETIVO"
        RCBObjetivo.DataValueField = "CVEOBJETIVO"
        RCBObjetivo.DataBind()



        If RCBObjetivo.Enabled = False Then
            LlenarIniciativas()
        End If
    End Sub

    Sub LlenarIniciativas()
        RCBIniciativa.Items.Clear()
        'Dim CONSULTA As String
        'CONSULTA = "SELECT CVEINICIATIVA, INICIATIVA FROM TblPAIniciativa WHERE CVEPLAN=" & RCBPlan.SelectedValue & " AND CVEOBJETIVO=" & RCBObjetivo.SelectedValue & " AND CVEINICIATIVA=" & CveIniciativa & " AND ANIOESTUDIO=" & AnioEstudio
        'Cargar.ComboSentenciaTxt(RCBIniciativa, CONSULTA, "INICIATIVA", "CVEINICIATIVA", 2, False)


        Dim ds As New DataSet
        Dim P(4) As SqlParameter
        P(0) = New SqlParameter("@TIPO", 46)
        P(1) = New SqlParameter("@CVEPLAN", RCBPlan.SelectedValue)
        P(2) = New SqlParameter("@CVEOBJETIVO", RCBObjetivo.SelectedValue)
        P(3) = New SqlParameter("@CVEINICIATIVA", CveIniciativa)
        P(4) = New SqlParameter("@ANIOESTUDIO", AnioEstudio)
        ds = DatosBD.FuncionConPar("SP_CONSULTAS_ENTREGAVIRTUAL", P, Lerror.Text)


        RCBIniciativa.DataSource = ds.Tables(0)
        RCBIniciativa.DataTextField = "INICIATIVA"
        RCBIniciativa.DataValueField = "CVEINICIATIVA"
        RCBIniciativa.DataBind()

    End Sub

    Sub LlenarGrid()
        Dim ds As DataSet
        Dim p(3) As SqlParameter
        p(0) = New SqlParameter("@CVEPLAN", RCBPlan.SelectedValue)
        p(1) = New SqlParameter("@TIPO", 4)
        p(2) = New SqlParameter("@CVEINICIATIVA", RCBIniciativa.SelectedValue)
        p(3) = New SqlParameter("@NUMUSUARIO", LNumUsuario.Text)
        ds = DatosBD.FuncionConPar("SP_PAConsultaPlan", p, Lerror.Text)

        RadGrid1.DataSource = ds.Tables(0)
        RadGrid1.DataBind()

        For cont As Integer = 0 To RadGrid1.MasterTableView.AutoGeneratedColumns.Length - 1
            Dim colDecimal As GridBoundColumn
            colDecimal = RadGrid1.MasterTableView.AutoGeneratedColumns(cont)
            colDecimal.HeaderStyle.Font.Bold = True
            colDecimal.HeaderStyle.HorizontalAlign = HorizontalAlign.Left
            colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Left

            If cont = 0 Then '
                colDecimal.Visible = False
            ElseIf cont = 1 Then '
                colDecimal.HeaderStyle.Width = 50
            ElseIf cont = 2 Then '
                colDecimal.HeaderStyle.Width = 200
            ElseIf cont = 3 Then '
                colDecimal.HeaderStyle.Width = 50
            ElseIf cont = 4 Then '
                colDecimal.HeaderStyle.Width = 200
            ElseIf cont = 5 Then '
                colDecimal.HeaderStyle.Width = 100
            ElseIf cont = 6 Then '
                colDecimal.HeaderStyle.Width = 200
            End If
        Next

        RadGrid1.Rebind()
    End Sub

    Protected Sub BGuardar_Click(ByVal sender As Object, ByVal e As EventArgs) Handles BGuardar.Click
        Lerror.Text = ""
        Dim ds As New DataSet
        Dim P(6) As SqlParameter
        P(0) = New SqlParameter("@TIPO", 3)
        P(1) = New SqlParameter("@CVEPLAN", RCBPlan.SelectedValue)
        P(2) = New SqlParameter("@CVEINICIATIVA", RCBIniciativa.SelectedValue)
        P(3) = New SqlParameter("@NOTASEVALUADOR", RTNotas.Text.Trim)
        P(4) = New SqlParameter("@CALIFICACION", RadRating1.Value)
        P(5) = New SqlParameter("@CVEPERFIL", 1)
        P(6) = New SqlParameter("@NUMUSUARIO", LNumUsuario.Text)
        ds = DatosBD.FuncionConPar("SP_PAEvaluaPlan", P, Lerror.Text)
        If Lerror.Text = "" Then
            Lerror.Text = "Se evaluó la iniciativa con éxito."
        End If
    End Sub
End Class
