Imports Telerik.Web.UI
Imports System.Web.UI.DataVisualization.Charting
Imports System.Drawing
Imports System.Data.SqlClient

Partial Public Class PantallaCompleta
    Inherits System.Web.UI.Page

    Protected Overrides Sub InitializeCulture()
        If Not Session("Lenguaje") Is Nothing Then
            UICulture = Session("Lenguaje")
            Culture = Session("Lenguaje")
        End If
        MyBase.InitializeCulture()
    End Sub

    Dim NumReporte As String

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        If Session("CON") = "OK" Then
            If Not Page.IsPostBack Then
                NumReporte = Request.Params("R")
                If Page.Request.Params("T") = "Clima" Then
                    ReportViewer1.Visible = False
                    BuildGrid()
                ElseIf Page.Request.Params("T") = "EngDemograficos" Then
                    ReportViewer1.Visible = False
                    MatrizDemograficos()
                ElseIf Page.Request.Params("T") = "Liderazgo" Then
                    RadGrid1.Visible = False
                    BuildReport()
                End If
            End If
        Else
            Session.Abandon()
            Response.Redirect("Acceso.aspx", True)
        End If
    End Sub

    Sub BuildGrid()

        Dim Reporte As String
        Reporte = Request.Params("R")
        Dim DT As DataTable
        DT = CType(Session("DTPantalla"), DataTable)
        RadGrid1.DataSource = DT


        Dim expression1 As GridGroupByExpression
        RadGrid1.MasterTableView.GroupByExpressions.Clear()

        RadGrid1.DataBind()

        If Reporte = "6" Then
            For cont As Integer = 0 To RadGrid1.MasterTableView.AutoGeneratedColumns.Length - 1
                Dim colDecimal As GridBoundColumn
                colDecimal = RadGrid1.MasterTableView.AutoGeneratedColumns(cont)
                colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Center
                colDecimal.Visible = True
                If cont = 0 Or cont = 1 Then 'Quitamos el tema de la tabla
                    colDecimal.Visible = False
                ElseIf cont = 2 Then 'CvePregunta
                    colDecimal.HeaderStyle.Width = 50
                ElseIf cont = 3 Then 'DescPregunta
                    colDecimal.HeaderStyle.Width = 600
                    colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Left
                ElseIf cont = 4 Then 'Personas
                    colDecimal.HeaderStyle.Width = 50
                ElseIf cont = 5 Then 'Promedio
                    colDecimal.HeaderStyle.Width = 100
                    colDecimal.DataFormatString = "{0:N1}"
                End If
            Next
            expression1 = GridGroupByExpression.Parse("NOMTEMA [" & GETPALABRA("Tema") & "] GROUP BY CVETEMA")
        ElseIf Reporte = "8" Then
            For cont As Integer = 0 To RadGrid1.MasterTableView.AutoGeneratedColumns.Length - 1
                Dim colDecimal As GridBoundColumn
                colDecimal = RadGrid1.MasterTableView.AutoGeneratedColumns(cont)
                colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Center
                colDecimal.Visible = True
                colDecimal.HeaderStyle.Wrap = True
                If cont >= 4 Then 'Niveles
                    colDecimal.HeaderStyle.Width = 75
                    If cont Mod 2 = 1 Then
                        colDecimal.DataFormatString = "{0:N1}"
                    End If
                Else
                    If cont = 0 Or cont = 1 Then 'Quitamos el tema de la tabla
                        colDecimal.Visible = False
                    ElseIf cont = 2 Then 'CveDepto
                        colDecimal.HeaderStyle.Width = 50
                    ElseIf cont = 3 Then 'NomDepto
                        colDecimal.HeaderStyle.Width = 150
                        colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Left
                    End If
                End If
            Next
            expression1 = GridGroupByExpression.Parse("NOMTEMA [" & GETPALABRA("Tema") & "] GROUP BY CVETEMA")
        ElseIf Reporte = "11" Then
            For cont As Integer = 0 To RadGrid1.MasterTableView.AutoGeneratedColumns.Length - 1
                Dim colDecimal As GridBoundColumn
                colDecimal = RadGrid1.MasterTableView.AutoGeneratedColumns(cont)
                colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Center
                colDecimal.Visible = True
                If cont = 0 Or cont = 1 Then 'Quitamos el tema de la tabla
                    colDecimal.Visible = False
                ElseIf cont = 2 Then 'CvePregunta
                    colDecimal.HeaderStyle.Width = 50
                ElseIf cont = 3 Then 'DescPregunta
                    colDecimal.HeaderStyle.Width = 600
                    colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Left
                ElseIf cont = 4 Then 'Sindicalizados
                    colDecimal.HeaderStyle.Width = 100
                    colDecimal.DataFormatString = "{0:N1}"
                ElseIf cont = 5 Then 'No Sindicalizados
                    colDecimal.HeaderStyle.Width = 100
                    colDecimal.DataFormatString = "{0:N1}"
                ElseIf cont = 6 Then 'Total Empresa
                    colDecimal.HeaderStyle.Width = 100
                    colDecimal.DataFormatString = "{0:N1}"
                End If
            Next
            expression1 = GridGroupByExpression.Parse("NOMTEMA [" & GETPALABRA("Tema") & "] GROUP BY CVETEMA")
        ElseIf Reporte = "12" Then
            For cont As Integer = 0 To RadGrid1.MasterTableView.AutoGeneratedColumns.Length - 1
                Dim colDecimal As GridBoundColumn
                colDecimal = RadGrid1.MasterTableView.AutoGeneratedColumns(cont)
                colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Center
                colDecimal.Visible = True
                If cont = 0 Or cont = 1 Then 'Quitamos las preguntas
                    colDecimal.Visible = False
                ElseIf cont = 2 Then 'CveDepto
                    colDecimal.HeaderStyle.Width = 50
                ElseIf cont = 3 Then 'NomDepto
                    colDecimal.HeaderStyle.Width = 100
                    colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Left
                ElseIf cont >= 4 Then 'Respuestas
                    colDecimal.HeaderStyle.Width = 100
                End If
            Next
            expression1 = GridGroupByExpression.Parse("DESCPREGUNTA [P ] GROUP BY CVEPREGUNTA")
        ElseIf Reporte = "3" Then
            For cont As Integer = 0 To RadGrid1.MasterTableView.AutoGeneratedColumns.Length - 1
                Dim colDecimal As GridBoundColumn
                colDecimal = RadGrid1.MasterTableView.AutoGeneratedColumns(cont)
                colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Center
                colDecimal.Visible = True
                If cont >= 4 Then 'Niveles
                    colDecimal.HeaderStyle.Width = 100
                    colDecimal.DataFormatString = "{0:N1}"
                Else
                    If cont = 0 Or cont = 1 Then 'Quitamos el tema de la tabla
                        colDecimal.Visible = False
                    ElseIf cont = 2 Then 'CvePregunta
                        colDecimal.HeaderStyle.Width = 50
                    ElseIf cont = 3 Then 'DescPregunta
                        colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Left
                        colDecimal.HeaderStyle.Width = 600
                    End If
                End If
            Next
            expression1 = GridGroupByExpression.Parse("NOMTEMA [" & GETPALABRA("Tema") & "] GROUP BY CVETEMA")
        ElseIf Reporte = "3_Todos" OrElse Reporte = "3_General" OrElse Reporte = "23" OrElse Reporte = "24" OrElse Reporte = "25" OrElse Reporte = "26" Or Reporte = "31" Then
            For cont As Integer = 0 To RadGrid1.MasterTableView.AutoGeneratedColumns.Length - 1
                Dim colDecimal As GridBoundColumn
                colDecimal = RadGrid1.MasterTableView.AutoGeneratedColumns(cont)
                colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Center
                colDecimal.Visible = True
                If cont >= 4 Then 'Departamentos y/o Niveles
                    colDecimal.HeaderStyle.Width = 100
                    colDecimal.HeaderStyle.Wrap = True
                    colDecimal.DataFormatString = "{0:N1}"
                Else
                    If cont = 0 Or cont = 1 Then 'Quitamos el tema de la tabla
                        colDecimal.Visible = False
                    ElseIf cont = 2 Then 'CvePregunta
                        colDecimal.HeaderStyle.Width = 50
                    ElseIf cont = 3 Then  'DescPregunta
                        colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Left
                        colDecimal.HeaderStyle.Width = 600
                    End If
                End If
            Next
            expression1 = GridGroupByExpression.Parse("NOMTEMA [" & GETPALABRA("Tema") & "] GROUP BY CVETEMA")
        ElseIf Reporte = "21" OrElse Reporte = "22" Then
            For cont As Integer = 0 To RadGrid1.MasterTableView.AutoGeneratedColumns.Length - 1
                Dim colDecimal As GridBoundColumn
                colDecimal = RadGrid1.MasterTableView.AutoGeneratedColumns(cont)
                colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Center
                colDecimal.Visible = True
                If cont = 4 Then 'Promedio
                    colDecimal.HeaderStyle.Width = 50
                    colDecimal.DataFormatString = "{0:N1}"
                Else
                    If cont = 0 Or cont = 1 Then 'Quitamos el tema de la tabla
                        colDecimal.Visible = False
                    ElseIf cont = 2 Then 'CvePregunta
                        colDecimal.HeaderStyle.Width = 50
                    ElseIf cont = 3 Then 'DescPregunta
                        colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Left
                        colDecimal.HeaderStyle.Width = 600
                    End If
                End If
            Next
            expression1 = GridGroupByExpression.Parse("NOMTEMA [" & GETPALABRA("Tema") & "] GROUP BY CVETEMA")
        ElseIf Reporte = "40" Then
            For cont As Integer = 0 To RadGrid1.MasterTableView.AutoGeneratedColumns.Length - 1
                Dim colDecimal As GridBoundColumn
                colDecimal = RadGrid1.MasterTableView.AutoGeneratedColumns(cont)
                colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Center
                colDecimal.Visible = True
                If cont = 4 Then
                    colDecimal.HeaderStyle.Width = 100
                    colDecimal.DataFormatString = "{0:P1}"
                    colDecimal.ItemStyle.Font.Bold = True
                Else
                    If cont = 0 Or cont = 1 Then 'Quitamos el componente de la tabla
                        colDecimal.Visible = False
                    ElseIf cont = 2 Then
                        colDecimal.HeaderStyle.Width = 50
                    Else
                        colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Left
                        colDecimal.HeaderStyle.Width = 400
                    End If
                End If
            Next
            expression1 = GridGroupByExpression.Parse("COMPONENTE [Componente] GROUP BY COMPONENTE")
        End If

        Try
            ' Dim expression1 As GridGroupByExpression = GridGroupByExpression.Parse("NOMTEMA [Tema] GROUP BY CVETEMA")
            Me.RadGrid1.MasterTableView.GroupByExpressions.Add(expression1)
            Me.RadGrid1.MasterTableView.GroupsDefaultExpanded = False
        Catch ex As Exception
            Lerror.Text = String.Format("<span style='color:red'>Cannot add group by expression: {0}</span>", ex.Message)
            Lerror.Visible = True
        Finally
            RadGrid1.Rebind()
            RadGrid1.Visible = True
        End Try
    End Sub

    Private Sub BuildReport()
        'Dim NumReporte As String
        NumReporte = Request.Params("R")
        Dim DT As DataTable
        DT = CType(Session("DTPantalla"), DataTable)


        If NumReporte = 15 Then
            ReportViewer1.Report = New R15
        ElseIf NumReporte = 16 Then
            ReportViewer1.Report = New R16
        ElseIf NumReporte = 17 Then
            ReportViewer1.Report = New R17
        ElseIf NumReporte = 18 Then
            ReportViewer1.Report = New R18
        ElseIf NumReporte = 19 Then
            ReportViewer1.Report = New R19
        ElseIf NumReporte = 20 Then
            ReportViewer1.Report = New R20
        ElseIf NumReporte = 13 Then
            ReportViewer1.Report = New R13
        ElseIf NumReporte = 39 Or NumReporte = 38 Then
            ReportViewer1.Report = New MatrizEfectividad
        End If

        ReportViewer1.Visible = True
        ReportViewer1.ZoomPercent = 80

        'Set the parameters
        Dim NomEmpresa As String
        Dim NomReporte As String
        NomEmpresa = Session("NombreEmpresa")
        'Dim con2 As String = "SELECT UPPER(NOMREPORTE) FROM TBLREPORTES_ENTREGAVIRTUAL WHERE ORDEN=" & NumReporte & ""

        'ds2 = DatosBD.FuncionTXT(con2, "")

        Dim ds2 As New DataSet
        Dim P(1) As SqlParameter
        P(0) = New SqlParameter("@TIPO", 47)
        P(1) = New SqlParameter("@NUMREPORTE", NumReporte)
        ds2 = DatosBD.FuncionConPar("SP_CONSULTAS_ENTREGAVIRTUAL", P, Lerror.Text)



        NomReporte = ds2.Tables(0).Rows(0).Item(0)

        If NumReporte = 13 Then
            Dim ds3 As New DataSet
            Dim T_Comentarios As Integer
            Dim T_Molestias As Integer

            'Dim con3 As String = "SELECT 13 CVEPREGUNTA, COUNT(*) TOTAL FROM TBLRESPUESTADADATEXTO WHERE CVEEMPRESA=" & Session("CveEmpresa") & " AND CVEPREGUNTA=13 UNION SELECT 14 CVEPREGUNTA, COUNT(*) TOTAL FROM TBLRESPUESTADADATEXTO WHERE CVEEMPRESA=" & Session("CveEmpresa") & " AND CVEPREGUNTA=14 ORDER BY CVEPREGUNTA"


            Dim P2(1) As SqlParameter
            P2(0) = New SqlParameter("@TIPO", 48)
            P2(1) = New SqlParameter("@CVEEMPRESA", Session("CveEmpresa"))
            ds3 = DatosBD.FuncionConPar("SP_CONSULTAS_ENTREGAVIRTUAL", P2, Lerror.Text)

            'ds3 = DatosBD.FuncionTXT(con3, "")

            T_Comentarios = ds3.Tables(0).Rows(0).Item(1)
            T_Molestias = ds3.Tables(0).Rows(1).Item(1)

            ReportViewer1.Report.ReportParameters(0).Value = NomEmpresa
            ReportViewer1.Report.ReportParameters(1).Value = NomReporte
            ReportViewer1.Report.ReportParameters(2).Value = CInt(Session("CveEmpresa"))
            ReportViewer1.Report.ReportParameters(3).Value = CInt(Session("CveEncuesta"))
            ReportViewer1.Report.ReportParameters(4).Value = T_Comentarios
            ReportViewer1.Report.ReportParameters(5).Value = T_Molestias
        Else
            ReportViewer1.Report.ReportParameters(0).Value = NomEmpresa
            ReportViewer1.Report.ReportParameters(1).Value = NomReporte
            ReportViewer1.Report.ReportParameters(2).Value = CInt(Session("CveEmpresa"))
            ReportViewer1.Report.ReportParameters(3).Value = CInt(Session("CveEncuesta"))
        End If

        ReportViewer1.Report.Reports(0).DataSource = DT
        ReportViewer1.RefreshReport()
    End Sub

    Sub MatrizDemograficos()
        Dim DT As DataTable
        DT = CType(Session("DTPantalla"), DataTable)
        RadGrid1.DataSource = DT
        RadGrid1.DataBind()
        RadGrid1.Visible = True

        For cont As Integer = 0 To RadGrid1.MasterTableView.AutoGeneratedColumns.Length - 1
            Dim colDecimal As GridBoundColumn
            colDecimal = RadGrid1.MasterTableView.AutoGeneratedColumns(cont)
            colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Center
            colDecimal.Visible = True
            If cont = 0 Then 'Quitamos la clave
                colDecimal.Visible = False
            ElseIf cont = 1 Then 'Descripcion
                colDecimal.HeaderStyle.Width = 200
                colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Center
            ElseIf cont >= 2 Then 'Perfiles de Efectividad
                colDecimal.HeaderStyle.Width = 100
                colDecimal.DataFormatString = "{0:P1}"
            End If
        Next
        RadGrid1.Rebind()
    End Sub

    Private Sub RadGrid1_ItemDataBound(ByVal sender As Object, ByVal e As Telerik.Web.UI.GridItemEventArgs) Handles RadGrid1.ItemDataBound
        If e.Item.ItemType = GridItemType.Header Then
            'e.Item.Cells(8).Width = 150
            'e.Item.BackColor = Color.Blue
        ElseIf e.Item.ItemType = GridItemType.GroupHeader Then
            'e.Item.Width = 100
            e.Item.BackColor = Color.LightSteelBlue
        ElseIf e.Item.ItemType = Telerik.Web.UI.GridItemType.Item OrElse e.Item.ItemType = Telerik.Web.UI.GridItemType.AlternatingItem Then
            If NumReporte = "43" Then 'Reporte para identificar prioridades 
                e.Item.Cells(4).BackColor = GETCOLOR3(e.Item.Cells(4).Text)
                e.Item.Cells(4).ForeColor = GETCOLOR4(e.Item.Cells(4).Text)

                e.Item.Cells(5).BackColor = GETCOLOR3(e.Item.Cells(5).Text)
                e.Item.Cells(5).ForeColor = GETCOLOR4(e.Item.Cells(5).Text)
            ElseIf NumReporte = "27" Or NumReporte = "28" Or NumReporte = "29" Or NumReporte = "30" Then 'Matriz Demograficos 
                e.Item.Cells(4).ForeColor = Color.Green
                e.Item.Cells(5).ForeColor = Color.Blue
                e.Item.Cells(6).ForeColor = Color.Orange
                e.Item.Cells(7).ForeColor = Color.Red

                e.Item.Cells(4).Font.Bold = True
                e.Item.Cells(5).Font.Bold = True
                e.Item.Cells(6).Font.Bold = True
                e.Item.Cells(7).Font.Bold = True
            Else
                For N As Integer = 4 To e.Item.Cells.Count - 1
                    If IsNumeric(e.Item.Cells(N).Text) And e.Item.Cells(N).Text.Contains(".") Then
                        e.Item.Cells(N).BackColor = GETCOLOR(e.Item.Cells(N).Text)
                        e.Item.Cells(N).ForeColor = GETCOLOR2(e.Item.Cells(N).Text)
                    End If
                Next
                If e.Item.Cells(5).Text = "999" Then ' SI ES GENERAL
                    e.Item.Font.Bold = True
                End If
            End If
        ElseIf e.Item.ItemType = GridItemType.Footer Then

        End If
    End Sub

    Function GETCOLOR(ByVal Numero As Double) As System.Drawing.Color
        If Numero = 0 Then
            Return Drawing.Color.Gray
        ElseIf Numero > 0 And Numero <= 69.999999 Then
            Return Drawing.Color.Red
        ElseIf Numero >= 70.0 And Numero <= 79.999999 Then
            Return Drawing.Color.Yellow
        ElseIf Numero >= 80.0 And Numero <= 89.999999 Then
            Return Drawing.Color.Blue
        Else
            Return Drawing.Color.Green
        End If
    End Function

    Function GETCOLOR2(ByVal Numero As Double) As System.Drawing.Color
        If Numero = 0 Then
            Return Drawing.Color.White
        ElseIf Numero > 0 And Numero <= 69.999999 Then
            Return Drawing.Color.White
        ElseIf Numero >= 70.0 And Numero <= 79.999999 Then
            Return Drawing.Color.Black
        ElseIf Numero >= 80.0 And Numero <= 89.999999 Then
            Return Drawing.Color.White
        Else
            Return Drawing.Color.White
        End If
    End Function

    Function GETCOLOR3(ByVal Numero As Integer) As System.Drawing.Color
        If Numero = 1 Or Numero = 2 Then
            Return Drawing.Color.Red
        ElseIf Numero = 3 Or Numero = 4 Then
            Return Drawing.Color.Yellow
        ElseIf Numero = 5 Or Numero = 6 Then
            Return Drawing.Color.Blue
        ElseIf Numero = 7 Or Numero = 8 Then
            Return Drawing.Color.Green
        Else
            Return Drawing.Color.Gray
        End If
    End Function

    Function GETCOLOR4(ByVal Numero As Integer) As System.Drawing.Color
        If Numero = 1 Or Numero = 2 Then
            Return Drawing.Color.White
        ElseIf Numero = 3 Or Numero = 4 Then
            Return Drawing.Color.Black
        ElseIf Numero = 5 Or Numero = 6 Then
            Return Drawing.Color.White
        ElseIf Numero = 7 Or Numero = 8 Then
            Return Drawing.Color.White
        Else
            Return Drawing.Color.White
        End If
    End Function

    Function GETPALABRA(ByVal Palabra As String) As String
        Dim Traduccion As String
        Dim DS As DataSet
        Dim P(1) As SqlParameter
        P(0) = New SqlParameter("@IDIOMA", Session("Lenguaje"))
        P(1) = New SqlParameter("@PALABRA", Palabra)
        DS = DatosBD.FuncionConPar("SP_GETTRADUCCION", P, Lerror.Text)
        Traduccion = DS.Tables(0).Rows(0).Item(0)
        Return Traduccion
    End Function
End Class