Imports System.Web.UI.DataVisualization.Charting
Imports System.Drawing
Imports System.Data.SqlClient
Imports Telerik.Web.UI

Partial Public Class PAPreguntas
    Inherits System.Web.UI.Page

    Protected Overrides Sub InitializeCulture()
        If Not Session("Lenguaje") Is Nothing Then
            UICulture = Session("Lenguaje")
            Culture = Session("Lenguaje")
        End If
        MyBase.InitializeCulture()
    End Sub

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        If Session("CON") = "OK" Then
            If Not Page.IsPostBack Then
                Session("CveIniciativa") = Page.Request.Params("Ini")
                Session("CvePlan") = Page.Request.Params("P")
                LlenarGrid()
            End If
        Else
            Session.Abandon()
            Response.Redirect("Acceso.aspx", True)
        End If
    End Sub

    Sub LlenarGrid()
        Dim ds As New DataSet
        Dim P(4) As SqlParameter
        P(0) = New SqlParameter("@TIPO", 1)
        P(1) = New SqlParameter("@CVEPLAN", Session("CvePlan"))
        P(2) = New SqlParameter("@CVEPERFIL", Session("NUMPERFIL"))
        P(3) = New SqlParameter("@CVEINICIATIVA", Session("CveIniciativa"))
        P(4) = New SqlParameter("@USUARIO", Session("NUMUSUARIO"))
        ds = DatosBD.FuncionConPar("sp_PAConsultaPreguntas", P, Lerror.Text)

        Dim TBLREPORTE As DataTable = ds.Tables(0)
        RadGrid1.MasterTableView.GroupByExpressions.Clear()
        RadGrid1.DataSource = TBLREPORTE
        RadGrid1.DataBind()

        For cont As Integer = 0 To RadGrid1.MasterTableView.AutoGeneratedColumns.Length - 1
            Dim colDecimal As GridBoundColumn
            colDecimal = RadGrid1.MasterTableView.AutoGeneratedColumns(cont)
            colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Center
            colDecimal.Visible = True
            If cont = 0 Then 'CveTema
                colDecimal.Visible = False
            ElseIf cont = 1 Then 'Tema
                colDecimal.HeaderStyle.Width = 100
                colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Left
            ElseIf cont = 2 Then 'CvePregunta
                colDecimal.Visible = False
            ElseIf cont = 3 Then 'Pregunta
                colDecimal.HeaderStyle.Width = 400
                colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Left
            ElseIf cont = 4 Then 'Chk
                colDecimal.Visible = False
            ElseIf cont = 5 Then 'Compromiso
                colDecimal.HeaderStyle.Width = 50
            ElseIf cont = 6 Then 'Soporte
                colDecimal.HeaderStyle.Width = 50
            End If
        Next
    End Sub

    Protected Sub BGuardar_Click(ByVal sender As Object, ByVal e As EventArgs) Handles BGuardar.Click
        'Dim sentencia As String
        'sentencia = "DELETE FROM TblPAPregunta WHERE CvePlan=" & Session("CvePlan") & " AND CveIniciativa=" & Session("CveIniciativa") & " AND AnioEstudio=DBO.GETANIOPLAN(" & Session("NUMUSUARIO") & ")"
        'DatosBD.ProcedimientoTXT(sentencia, "")


        Dim ds As New DataSet
        Dim P(3) As SqlParameter
        P(0) = New SqlParameter("@TIPO", 49)
        P(1) = New SqlParameter("@CVEPLAN", Session("CvePlan"))
        P(2) = New SqlParameter("@CVEINICIATIVA", Session("CveIniciativa"))
        P(3) = New SqlParameter("@USUARIO", Session("NUMUSUARIO"))
        ds = DatosBD.FuncionConPar("SP_CONSULTAS_ENTREGAVIRTUAL", P, Lerror.Text)


        For i As Integer = 0 To RadGrid1.Items.Count - 1
            Dim Check As New CheckBox
            Check = CType(RadGrid1.Items(i).Cells(2).Controls(1), CheckBox)
            If Check.Checked = True Then
                Dim ds2 As New DataSet
                Dim P2(3) As SqlParameter
                P2(0) = New SqlParameter("@CVEPLAN", Session("CvePlan"))
                P2(1) = New SqlParameter("@CVEINICIATIVA", Session("CveIniciativa"))
                P2(2) = New SqlParameter("@CVEPREGUNTA", RadGrid1.Items(i).Cells(5).Text)
                P2(3) = New SqlParameter("@NUMUSUARIO", Session("NUMUSUARIO"))
                ds2 = DatosBD.FuncionConPar("SP_PARelacionaPreguntas", P2, Lerror.Text)
            End If
        Next
        Lerror.Text = "Se realizó la relación de preguntas con éxito."
    End Sub

    Private Sub RadGrid1_ItemDataBound(ByVal sender As Object, ByVal e As Telerik.Web.UI.GridItemEventArgs) Handles RadGrid1.ItemDataBound
        If e.Item.ItemType = GridItemType.AlternatingItem OrElse e.Item.ItemType = GridItemType.Item Then
            Dim Chk As New CheckBox
            If e.Item.Cells(7).Text = 1 Then
                CType(e.Item.Cells(2).Controls(1), CheckBox).Checked = True
            End If

            e.Item.Cells(8).BackColor = GETCOLOR3(e.Item.Cells(8).Text)
            e.Item.Cells(8).ForeColor = GETCOLOR4(e.Item.Cells(8).Text)

            e.Item.Cells(9).BackColor = GETCOLOR3(e.Item.Cells(9).Text)
            e.Item.Cells(9).ForeColor = GETCOLOR4(e.Item.Cells(9).Text)
        End If
    End Sub

    Function GETCOLOR3(ByVal Numero As Integer) As System.Drawing.Color
        If Numero = 1 Or Numero = 2 Then
            Return Drawing.Color.Red
        ElseIf Numero = 3 Or Numero = 4 Then
            Return Drawing.Color.Yellow
        ElseIf Numero = 5 Or Numero = 6 Then
            Return Drawing.Color.Blue
        ElseIf Numero = 7 Or Numero = 8 Then
            Return Drawing.Color.Green
        Else
            Return Drawing.Color.Gray
        End If
    End Function

    Function GETCOLOR4(ByVal Numero As Integer) As System.Drawing.Color
        If Numero = 1 Or Numero = 2 Then
            Return Drawing.Color.White
        ElseIf Numero = 3 Or Numero = 4 Then
            Return Drawing.Color.Black
        ElseIf Numero = 5 Or Numero = 6 Then
            Return Drawing.Color.White
        ElseIf Numero = 7 Or Numero = 8 Then
            Return Drawing.Color.White
        Else
            Return Drawing.Color.White
        End If
    End Function
End Class