Imports System.Web.UI.DataVisualization.Charting
Imports System.Drawing
Imports System.Data.SqlClient
Imports Telerik.Web.UI

Partial Public Class ReporteDemograficos
    Inherits System.Web.UI.Page


    Protected Overrides Sub InitializeCulture()
        If Not Session("Lenguaje") Is Nothing Then
            UICulture = Session("Lenguaje")
            Culture = Session("Lenguaje")
        End If
        MyBase.InitializeCulture()
    End Sub

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        If Session("CON") = "OK" Then
            If Not Page.IsPostBack Then
                'BuildReport(Page.Request.Params("R"))
                ' Dim CONSULTA As String
                ' CONSULTA = "SELECT ORDEN, NOMSUBREPORTE FROM TblReportes_EntregaVirtual WHERE VISIBLE=1 AND CVESECCION='CO' AND NUMREPORTE='R6' ORDER BY ORDEN"
                ' Cargar.ComboSentenciaTxt(RCBSubreporte, CONSULTA, "NOMSUBREPORTE", "ORDEN", 2, False)

                Dim ds As New DataSet
                Dim P(1) As SqlParameter
                P(0) = New SqlParameter("@TIPO", 57)
                P(1) = New SqlParameter("@IDIOMA", Session("Lenguaje"))

                ' ds = DatosBD.FuncionConPar("SP_CONSULTAS_ENTREGAVIRTUAL", P, Lerror.Text)


                Cargar.ComboParametros(RCBSubreporte, "SP_CONSULTAS_ENTREGAVIRTUAL", P, "NOMSUBREPORTE", "ORDEN", 2, True, Session("Lenguaje"))


                'RCBSubreporte.DataSource = ds.Tables(0)
                'RCBSubreporte.DataTextField = "NOMSUBREPORTE"
                'RCBSubreporte.DataValueField = "ORDEN"
                'RCBSubreporte.DataBind()

            End If
        Else
            Session.Abandon()
            Response.Redirect("Acceso.aspx", True)
        End If
    End Sub

    Protected Sub RCBSubreporte_SelectedIndexChanged(ByVal sender As Object, ByVal e As Telerik.Web.UI.RadComboBoxSelectedIndexChangedEventArgs) Handles RCBSubreporte.SelectedIndexChanged
        BuildReport(RCBSubreporte.SelectedValue)
    End Sub

    Private Sub BuildReport(ByVal NumReporte As String)
        Try
            Dim ds As New DataSet
            Dim Stored As String
            If NumReporte = "23" Then
                Stored = "SP_RepDemoEdad"
            ElseIf NumReporte = "24" Then
                Stored = "SP_RepDemoAntiguedad"
            ElseIf NumReporte = "25" Then
                Stored = "SP_RepDemoEstudios"
            ElseIf NumReporte = "26" Then
                Stored = "SP_RepDemoGenero"
            End If

            Dim PLoad(11) As SqlParameter
            PLoad(0) = New SqlParameter("@CVEDIVISION", Session("CveUnidad"))
            PLoad(1) = New SqlParameter("@CVEAGRUPADOPAIS", Session("CveAgrupado"))
            PLoad(2) = New SqlParameter("@CVEPAIS", Session("CvePais"))
            PLoad(3) = New SqlParameter("@CVEAREA", Session("CveTipo"))
            PLoad(4) = New SqlParameter("@CVETERRITORIO", Session("CveTerritorio"))
            PLoad(5) = New SqlParameter("@CVEREGION", Session("CveRegion"))
            PLoad(6) = New SqlParameter("@CVESUBREGION", Session("CveSubRegion"))
            PLoad(7) = New SqlParameter("@CVEEMPRESA", DBNull.Value)
            PLoad(8) = New SqlParameter("@CVESISTEMA", Session("CveSistema"))
            PLoad(9) = New SqlParameter("@CVEPERFIL", Session("NUMPERFIL"))
            PLoad(10) = New SqlParameter("@USUARIO", Session("USUARIO"))

            If Session("Lenguaje") = "pt-BR" Then
                PLoad(11) = New SqlParameter("@IDIOMA", 2)
            ElseIf Session("Lenguaje") = "en-US" Then
                PLoad(11) = New SqlParameter("@IDIOMA", 11)
            Else
                PLoad(11) = New SqlParameter("@IDIOMA", 99)
            End If

            ds = DatosBD.FuncionConPar(Stored, PLoad, Lerror.Text)


            If Session("Lenguaje") = "en-US" Then
                ds.Tables(0).Columns(2).ColumnName = "Code"
                ds.Tables(0).Columns(3).ColumnName = "Questión"

                If Stored = "SP_RepDemoGenero" Then
                    ds.Tables(0).Columns(4).ColumnName = "Female"
                    ds.Tables(0).Columns(5).ColumnName = "Male"
                End If
            End If


            RadGrid1.DataSource = ds.Tables(0)
            Dim expression1 As GridGroupByExpression
            RadGrid1.MasterTableView.GroupByExpressions.Clear()
            RadGrid1.DataBind()

            For cont As Integer = 0 To RadGrid1.MasterTableView.AutoGeneratedColumns.Length - 1
                Dim colDecimal As GridBoundColumn
                colDecimal = RadGrid1.MasterTableView.AutoGeneratedColumns(cont)
                colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Center
                colDecimal.Visible = True
                If cont >= 4 Then
                    colDecimal.HeaderStyle.Width = 100
                    colDecimal.DataFormatString = "{0:N1}"
                Else
                    If cont = 0 Or cont = 1 Then 'Quitamos el tema de la tabla
                        colDecimal.Visible = False
                    ElseIf cont = 2 Then
                        colDecimal.HeaderStyle.Width = 50
                    Else
                        colDecimal.ItemStyle.HorizontalAlign = HorizontalAlign.Left
                        colDecimal.HeaderStyle.Width = 400
                    End If
                End If
            Next



            If Session("Lenguaje") = "pt-BR" Then
                expression1 = GridGroupByExpression.Parse("NOMTEMA [Tema] GROUP BY CVETEMA")
            ElseIf Session("Lenguaje") = "en-US" Then
                expression1 = GridGroupByExpression.Parse("NOMTEMA [Category] GROUP BY CVETEMA")
            Else
                expression1 = GridGroupByExpression.Parse("NOMTEMA [Tema] GROUP BY CVETEMA")
            End If

            Try
                ' Dim expression1 As GridGroupByExpression = GridGroupByExpression.Parse("NOMTEMA [Tema] GROUP BY CVETEMA")
                Me.RadGrid1.MasterTableView.GroupByExpressions.Add(expression1)
                Me.RadGrid1.MasterTableView.GroupsDefaultExpanded = True
            Catch ex As Exception
                Lerror.Text = String.Format("<span style='color:red'>Cannot add group by expression: {0}</span>", ex.Message)
                Lerror.Visible = True
            Finally
                RadGrid1.Rebind()
                RadGrid1.Visible = True
            End Try

        Catch ex As Exception
            Lerror.Text = "No existe información para este reporte."
        End Try
    End Sub

    Private Sub RadGrid1_ItemDataBound(ByVal sender As Object, ByVal e As Telerik.Web.UI.GridItemEventArgs) Handles RadGrid1.ItemDataBound
        If e.Item.ItemType = GridItemType.GroupHeader Then
            'e.Item.Width = 100
            e.Item.BackColor = Color.LightSteelBlue
        ElseIf e.Item.ItemType = Telerik.Web.UI.GridItemType.Item OrElse e.Item.ItemType = Telerik.Web.UI.GridItemType.AlternatingItem Then
            For N As Integer = 4 To e.Item.Cells.Count - 1
                If IsNumeric(e.Item.Cells(N).Text) And e.Item.Cells(N).Text.Contains(".") Then
                    e.Item.Cells(N).BackColor = GETCOLOR(e.Item.Cells(N).Text)
                    e.Item.Cells(N).ForeColor = GETCOLOR2(e.Item.Cells(N).Text)
                End If
            Next
            If e.Item.Cells(5).Text = "999" Then ' SI ES GENERAL
                e.Item.Font.Bold = True
            End If
        End If
    End Sub

    Function GETCOLOR(ByVal Numero As Double) As System.Drawing.Color
        If Numero = 0 Then
            Return Drawing.Color.Gray
        ElseIf Numero > 0 And Numero <= 69.999999 Then
            Return Drawing.Color.DarkRed
        ElseIf Numero >= 70.0 And Numero <= 79.999999 Then
            Return Drawing.Color.Goldenrod
        ElseIf Numero >= 80.0 And Numero <= 89.999999 Then
            Return Drawing.Color.DarkBlue
        Else
            Return Drawing.Color.DarkGreen
        End If
    End Function

    Function GETCOLOR2(ByVal Numero As Double) As System.Drawing.Color
        If Numero = 0 Then
            Return Drawing.Color.White
        ElseIf Numero > 0 And Numero <= 69.999999 Then
            Return Drawing.Color.White
        ElseIf Numero >= 70.0 And Numero <= 79.999999 Then
            Return Drawing.Color.Black
        ElseIf Numero >= 80.0 And Numero <= 89.999999 Then
            Return Drawing.Color.White
        Else
            Return Drawing.Color.White
        End If
    End Function

End Class